/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DailyEntryRouteImport } from './routes/daily-entry'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MastersProjectsRouteImport } from './routes/masters.projects'
import { Route as MastersDepartmentsRouteImport } from './routes/masters.departments'
import { Route as MastersContractorsRouteImport } from './routes/masters.contractors'
import { Route as MastersCategoriesRouteImport } from './routes/masters.categories'
import { Route as MastersAssignmentsRouteImport } from './routes/masters.assignments'
import { Route as MastersApprovalsRouteImport } from './routes/masters.approvals'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyEntryRoute = DailyEntryRouteImport.update({
  id: '/daily-entry',
  path: '/daily-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersProjectsRoute = MastersProjectsRouteImport.update({
  id: '/masters/projects',
  path: '/masters/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersDepartmentsRoute = MastersDepartmentsRouteImport.update({
  id: '/masters/departments',
  path: '/masters/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersContractorsRoute = MastersContractorsRouteImport.update({
  id: '/masters/contractors',
  path: '/masters/contractors',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCategoriesRoute = MastersCategoriesRouteImport.update({
  id: '/masters/categories',
  path: '/masters/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersAssignmentsRoute = MastersAssignmentsRouteImport.update({
  id: '/masters/assignments',
  path: '/masters/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersApprovalsRoute = MastersApprovalsRouteImport.update({
  id: '/masters/approvals',
  path: '/masters/approvals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/daily-entry': typeof DailyEntryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/masters/approvals': typeof MastersApprovalsRoute
  '/masters/assignments': typeof MastersAssignmentsRoute
  '/masters/categories': typeof MastersCategoriesRoute
  '/masters/contractors': typeof MastersContractorsRoute
  '/masters/departments': typeof MastersDepartmentsRoute
  '/masters/projects': typeof MastersProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/daily-entry': typeof DailyEntryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/masters/approvals': typeof MastersApprovalsRoute
  '/masters/assignments': typeof MastersAssignmentsRoute
  '/masters/categories': typeof MastersCategoriesRoute
  '/masters/contractors': typeof MastersContractorsRoute
  '/masters/departments': typeof MastersDepartmentsRoute
  '/masters/projects': typeof MastersProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/daily-entry': typeof DailyEntryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/users': typeof UsersRoute
  '/masters/approvals': typeof MastersApprovalsRoute
  '/masters/assignments': typeof MastersAssignmentsRoute
  '/masters/categories': typeof MastersCategoriesRoute
  '/masters/contractors': typeof MastersContractorsRoute
  '/masters/departments': typeof MastersDepartmentsRoute
  '/masters/projects': typeof MastersProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/daily-entry'
    | '/login'
    | '/reports'
    | '/users'
    | '/masters/approvals'
    | '/masters/assignments'
    | '/masters/categories'
    | '/masters/contractors'
    | '/masters/departments'
    | '/masters/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/daily-entry'
    | '/login'
    | '/reports'
    | '/users'
    | '/masters/approvals'
    | '/masters/assignments'
    | '/masters/categories'
    | '/masters/contractors'
    | '/masters/departments'
    | '/masters/projects'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/daily-entry'
    | '/login'
    | '/reports'
    | '/users'
    | '/masters/approvals'
    | '/masters/assignments'
    | '/masters/categories'
    | '/masters/contractors'
    | '/masters/departments'
    | '/masters/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  DailyEntryRoute: typeof DailyEntryRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  UsersRoute: typeof UsersRoute
  MastersApprovalsRoute: typeof MastersApprovalsRoute
  MastersAssignmentsRoute: typeof MastersAssignmentsRoute
  MastersCategoriesRoute: typeof MastersCategoriesRoute
  MastersContractorsRoute: typeof MastersContractorsRoute
  MastersDepartmentsRoute: typeof MastersDepartmentsRoute
  MastersProjectsRoute: typeof MastersProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-entry': {
      id: '/daily-entry'
      path: '/daily-entry'
      fullPath: '/daily-entry'
      preLoaderRoute: typeof DailyEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/projects': {
      id: '/masters/projects'
      path: '/masters/projects'
      fullPath: '/masters/projects'
      preLoaderRoute: typeof MastersProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/departments': {
      id: '/masters/departments'
      path: '/masters/departments'
      fullPath: '/masters/departments'
      preLoaderRoute: typeof MastersDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/contractors': {
      id: '/masters/contractors'
      path: '/masters/contractors'
      fullPath: '/masters/contractors'
      preLoaderRoute: typeof MastersContractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/categories': {
      id: '/masters/categories'
      path: '/masters/categories'
      fullPath: '/masters/categories'
      preLoaderRoute: typeof MastersCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/assignments': {
      id: '/masters/assignments'
      path: '/masters/assignments'
      fullPath: '/masters/assignments'
      preLoaderRoute: typeof MastersAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/approvals': {
      id: '/masters/approvals'
      path: '/masters/approvals'
      fullPath: '/masters/approvals'
      preLoaderRoute: typeof MastersApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  DailyEntryRoute: DailyEntryRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  UsersRoute: UsersRoute,
  MastersApprovalsRoute: MastersApprovalsRoute,
  MastersAssignmentsRoute: MastersAssignmentsRoute,
  MastersCategoriesRoute: MastersCategoriesRoute,
  MastersContractorsRoute: MastersContractorsRoute,
  MastersDepartmentsRoute: MastersDepartmentsRoute,
  MastersProjectsRoute: MastersProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
